### ISSUE TITLE
demo21 怎么跑不起来？

### ISSUE THREAD

**Issue by loafer** [Tencent/kbone#156]

**Comment by JuneAndGreen** [comment]
app.json 多了个 logs 页面（被 gitignore 忽略），已去除。

> PS：后续提 issue 建议补上报错提示/截图，方便快速定位修复。

**Comment by loafer** [comment]
好的

**Comment by loafer** [comment]
@JuneAndGreen 还是跑不起来
VM26:1 thirdScriptError
module "package1/pages/page1/miniprogram-render" is not defined
Error: module "package1/pages/page1/miniprogram-render" is not defined
    at require (http://127.0.0.1:21569/appservice/__dev__/WAService.js:2:1718371)
    at http://127.0.0.1:21569/appservice/__dev__/WAService.js:2:1718122
    at http://127.0.0.1:21569/appservice/package1/pages/page1/index.js:3:10
    at require (http://127.0.0.1:21569/appservice/__dev__/WAService.js:2:1718512)
    at <anonymous>:14:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:21569/appservice/appservice?t=1586423777195:1192:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:21569/appservice/appservice?t=1586423777195:1204:20)

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/78972578-ab487f80-7b40-11ea-8081-8a7d4be079e1.png)
这两步执行了么？
