### ISSUE TITLE
Cannot set property 'constructor' of undefined

### ISSUE THREAD

**Issue by xiaohuoni** [Tencent/kbone#192]
有多生成一份css代码。
![image](https://user-images.githubusercontent.com/11746742/80329460-fb2f8200-8874-11ea-9485-8f08b67910bf.png)
在代码中也有引用
![image](https://user-images.githubusercontent.com/11746742/80329485-0d112500-8875-11ea-8c96-234ff998166a.png)
因为不识别css，所以我先手动删除了css的引用。
然后npm构建执行，之后出现了一个新的问题。
生成的代码：
```
onShareAppMessage(data) {
        const window = this.window
        if (window && window.onShareAppMessage) {
            const shareOptions = Object.assign({}, window.onShareAppMessage(data))

            if (shareOptions.miniprogramPath) {
                shareOptions.path = shareOptions.miniprogramPath
            } else {
                const query = Object.assign({}, this.query || {})
                let route = this.route

                if (shareOptions.path) {
                    shareOptions.path = shareOptions.path[0] === '/' ? window.location.origin + shareOptions.path : shareOptions.path
                    const {pathname} = window.location.constructor.$$parse(shareOptions.path)
                    const matchRoute = window.$$miniprogram.getMatchRoute(pathname || '/')
                    if (matchRoute) route = matchRoute
                    query.targeturl = encodeURIComponent(shareOptions.path)
                } else {
                    // 组装当前页面路径
                    const location = window.location

                    query.targeturl = encodeURIComponent(location.href)
                    query.search = encodeURIComponent(location.search)
                    query.hash = encodeURIComponent(location.hash)
                }

                query.type = 'share'
                const queryString = Object.keys(query).map(key => `${key}=${query[key] || ''}`).join('&')
                const currentPagePath = `${route}?${queryString}`
                shareOptions.path = currentPagePath
            }

            return shareOptions
        }
    },
```
有个错误：
```
Cannot set property 'constructor' of undefined;at "pages/umi/index" page lifeCycleMethod onLoad function
TypeError: Cannot set property 'constructor' of undefined
    at Object.ZSlt (http://127.0.0.1:15391/appservice/common/vendors~umi.js:1:332505)
    at a (http://127.0.0.1:15391/appservice/common/umi.js:1:1332)
    at Object.nDqD (http://127.0.0.1:15391/appservice/common/vendors~umi.js:1:522922)
    at a (http://127.0.0.1:15391/appservice/common/umi.js:1:1332)
    at Module.tB8F (http://127.0.0.1:15391/appservice/common/umi.js:1:120818)
    at a (http://127.0.0.1:15391/appservice/common/umi.js:1:1332)
    at Object.0 (http://127.0.0.1:15391/appservice/common/umi.js:1:2330)
    at a (http://127.0.0.1:15391/appservice/common/umi.js:1:1332)
    at K (http://127.0.0.1:15391/appservice/common/umi.js:1:1201)
    at A.createApp.0 (http://127.0.0.1:15391/appservice/common/umi.js:1:2296)
```
简略的 webpack 配置
```
const a  = { 
  mode: 'development',
  devtool: 'cheap-module-source-map',
  node:{ 
    setImmediate: false,
    module: 'empty',
    dns: 'mock',
    http2: 'empty',
    process: 'mock',
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty' 
  },
  output:{ 
    path: '/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/miniprogram/dist',
    filename: '[name].js',
    chunkFilename: '[name].js',
    publicPath: '/',
    futureEmitAssets: true,
    pathinfo: true 
  },
  resolve:{ 
    symlinks: true,
    alias:{ 
      'react-router':'/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/react-router',
      'react-router-dom':'/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/react-router-dom',
      history:'/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/history-with-query',
      '@': '/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/miniprogram',
      '@@': '/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/miniprogram/.umi',
      'regenerator-runtime':'/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/regenerator-runtime',
      react:'/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/react',
      'react-dom':'/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/react-dom',
      umi: '/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/umi' 
    },
    extensions:[ 
      '.web.js',
      '.wasm',
      '.mjs',
      '.js',
      '.web.jsx',
      '.jsx',
      '.web.ts',
      '.ts',
      '.web.tsx',
      '.tsx',
      '.json' ],
    modules:[ 
      'node_modules',
      '/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/node_modules/@umijs/bundler-webpack/node_modules' 
    ] 
  },
  module:{ 
    rules:[ 
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object] 
    ] 
  },
  plugins:[ 
    MiniCssExtractPlugin { options: [Object] },
    DefinePlugin { definitions: [Object] },
    WebpackBarPlugin {
       profile: false,
       handler: [Function],
       modulesCount: 500,
       showEntries: false,
       showModules: true,
       showActiveModules: true,
       options: [Object],
       reporters: [Array]
    },
    CopyPlugin { patterns: [], options: {} },
    FriendlyErrorsWebpackPlugin {
       compilationSuccessInfo: {},
       onErrors: undefined,
       shouldClearConsole: false,
       formatters: [Array],
       transformers: [Array] 
    },
    HotModuleReplacementPlugin {
       options: {},
       multiStep: undefined,
       fullBuildTimeout: 200,
       requestTimeout: 10000 
    } 
  ],
  entry:{ 
    umi:[ '/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/miniprogram/.umi/umi.ts' ] 
  } 
}
```
帮忙猜一猜，可能是什么错误！

**Comment by JuneAndGreen** [comment]
1、小程序里无法引入 css 文件，所以 webpack 配置请严格参考文档/demo/模板来，正常是不会生成 css 文件的。
2、constructor 报错看来是用的第三方库有个地方将 constructor 设置到一个不存在的对象上了。这个就目前的信息没法猜，你可以尝试在报错的栈上打个断点，看看是哪个不存在的对象被设置了 constructor。
