### ISSUE TITLE
某些情况下，报错，被上传到了 小程序后台的 运维中心 -> 错误查询

### ISSUE THREAD

**Issue by saoraozhe3hao** [Tencent/kbone#256]
Cannot read property '$$setCookie' of null
TypeError: Cannot read property '$$setCookie' of null
at n.value (https://miniprogram:///miniprogram_npm/miniprogram-render/bom/xml-http-request.js:148:40)
at Function.i.<computed> (https://lib/WASubContext.js:2:1602433)
at https://lib/WASubContext.js:2:111745
at k (https://lib/WASubContext.js:2:452127)
at Function.<anonymous> (https://lib/WASubContext.js:2:639391)
at https://lib/WASubContext.js:2:111745
at https://lib/WASubContext.js:2:627918

Cannot read property '$$setCookie' of null
TypeError: Cannot read property '$$setCookie' of null
at XMLHttpRequest.$_requestSuccess (weapp:///miniprogram_npm/miniprogram-render/bom/xml-http-request.js:180:34)
at Function.i.<computed> (eval at n.call.document (http://127.0.0.1:54490/remote-debug/runtime.js?devtools_ignore=true:1:1), <anonymous>:2:1742855)
at <api request success callback function>
at eval (eval at n.call.document (http://127.0.0.1:54490/remote-debug/runtime.js?devtools_ignore=true:1:1), <anonymous>:2:121490)
at k (eval at n.call.document (http://127.0.0.1:54490/remote-debug/runtime.js?devtools_ignore=true:1:1), <anonymous>:2:592549)
at Function.eval (eval at n.call.document (http://127.0.0.1:54490/remote-debug/runtime.js?devtools_ignore=true:1:1), <anonymous>:2:779873)
at <NetworkRequest71success callback function>
at eval (eval at n.call.document (http://127.0.0.1:54490/remote-debug/runtime.js?devtools_ignore=true:1:1), <anonymous>:2:121490)
at eval (eval at n.call.document (http://127.0.0.1:54490/remote-debug/runtime.js?devtools_ignore=true:1:1), <anonymous>:2:768400)
at Set.forEach (<anonymous>)

null is not an object (evaluating 'this.$_window.document.$$setCookie')
value@https://miniprogram:///miniprogram_npm/miniprogram-render/bom/xml-http-request.js:148:31
https://lib/WASubContext.js:2:1602481
https://lib/WASubContext.js:2:111745
k@https://lib/WASubContext.js:2:452127
https://lib/WASubContext.js:2:639450
https://lib/WASubContext.js:2:111745
https://lib/WASubContext.js:2:627982
value@https://lib/WASubContext.js:2:627955
N@https://lib/WASubContext.js:2:640400
https://lib/WASubContext.js:2:641728
https://lib/WASubContext.js:2:507745
https://lib/WAServiceMainContext.js:2:251579
_@https://lib/WAServiceMainContext.js:2:78181

**Comment by saoraozhe3hao** [comment]
我没有用到 $$setCookie

**Comment by JuneAndGreen** [comment]
看起来是有页面在 unload 之后仍然有请求创建，该页面是否存在“定时器 + 请求”的逻辑呢？
