### ISSUE TITLE
Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by githubmann** [Tencent/kbone#326]
Cannot read property 'fetch' of undefined
TypeError: Cannot read property 'fetch' of undefined
    at Object.<anonymous> (http://127.0.0.1:55784/appservice/common/vendors~index.js:26122:11)
    at __webpack_require__ (http://127.0.0.1:55784/appservice/common/index.js:81:30)
    at Module.176 (http://127.0.0.1:55784/appservice/common/index.js:1479:16)
    at __webpack_require__ (http://127.0.0.1:55784/appservice/common/index.js:81:30)
    at checkDeferredModules (http://127.0.0.1:55784/appservice/common/index.js:47:23)
    at http://127.0.0.1:55784/appservice/common/index.js:154:18
    at module.exports (http://127.0.0.1:55784/appservice/common/index.js:157:10)
    at init (http://127.0.0.1:55784/appservice/pages/index/index.js:21:35)
    at Ze.onLoad (http://127.0.0.1:55784/appservice/pages/base.js:207:7)
    at Ze.<anonymous> (http://127.0.0.1:55784/appservice/__dev__/WAService.js:2:2202993)

**Comment by githubmann** [comment]
```js
"use strict";

// CONCATENATED MODULE: ./node_modules/unfetch/src/index.mjs
/* harmony default export */ var src = (function(url, options) {
	options = options || {};
	return new Promise( (resolve, reject) => {
		const request = new XMLHttpRequest();
		const keys = [];
		const all = [];
		const headers = {};

		const response = () => ({
			ok: (request.status/100|0) == 2,		// 200-299
			statusText: request.statusText,
			status: request.status,
			url: request.responseURL,
			text: () => Promise.resolve(request.responseText),
			json: () => Promise.resolve(JSON.parse(request.responseText)),
			blob: () => Promise.resolve(new Blob([request.response])),
			clone: response,
			headers: {
				keys: () => keys,
				entries: () => all,
				get: n => headers[n.toLowerCase()],
				has: n => n.toLowerCase() in headers
			}
		});

		request.open(options.method || 'get', url, true);

		request.onload = () => {
			request.getAllResponseHeaders().replace(/^(.*?):[^\S\n]*([\s\S]*?)$/gm, (m, key, value) => {
				keys.push(key = key.toLowerCase());
				all.push([key, value]);
				headers[key] = headers[key] ? `${headers[key]},${value}` : value;
			});
			resolve(response());
		};

		request.onerror = reject;

		request.withCredentials = options.credentials=='include';

		for (const i in options.headers) {
			request.setRequestHeader(i, options.headers[i]);
		}

		request.send(options.body || null);
	});
});

// CONCATENATED MODULE: ./node_modules/unfetch/polyfill/polyfill.mjs

if (!self.fetch) self.fetch = src; // 报错


/***/ }),
```

**Comment by JuneAndGreen** [comment]
看来是 self 这个变量不存在，你改成 window.self 或者使用 globalVars 配置注入 self 变量即可。

或者直接更新 mp-webpack-plugin 到 1.1.18，里面已注入了 self 变量。
