### ISSUE TITLE
使用 Ant Design Mobile of React  小程序编译完报错

### ISSUE THREAD

**Issue by zdwork** [Tencent/kbone#337]
MiniProgramError
Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at Ze.onLoad (http://127.0.0.1:53031/appservice/pages/base.js:213:27)
    at Ze.<anonymous> (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:2202993)
    at Ze.p.__callPageLifeTime__ (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:2202738)
    at Dt (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:2218436)
    at http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:2222010
    at Mt (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:2222531)
    at Function.<anonymous> (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:2231471)
    at i.<anonymous> (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:2193682)
    at i.emit (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:680676)
    at Object.emit (http://127.0.0.1:53031/appservice/__dev__/WAService.js:2:662323)
errorReport @ VM323 WAService.js:2
thirdErrorReport @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
p.__callPageLifeTime__ @ VM323 WAService.js:2
Dt @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
Mt @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
i.emit @ VM323 WAService.js:2
emit @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
i.emit @ VM323 WAService.js:2
emit @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
(anonymous) @ VM323 WAService.js:2
c @ VM321 asdebug.js:1
l @ VM321 asdebug.js:1
(anonymous) @ VM321 asdebug.js:1
f @ VM321 asdebug.js:1
p @ VM321 asdebug.js:1
(anonymous) @ VM321 asdebug.js:1
_ws.onmessage @ VM321 asdebug.js:1

**Comment by JuneAndGreen** [comment]
因为 createApp 没有返回 app 导致，已在

 - mp-webpack-plugin@1.2.1

中进行兼容。
