### ISSUE TITLE
Webpack build Failed

### ISSUE THREAD

**Issue by DennisXH** [Tencent/kbone#363]
运行`npm run build` 报错
```
92% chunk asset optimization OptimizeCssAssetsWebpackPlugin[webpack-cli] TypeError: Cannot read property 'toFixed' of undefined
    at strongRound (/Users/dennis/work/github/wx-app/node_modules/svgo/plugins/convertPathData.js:766:21)
    at /Users/dennis/work/github/wx-app/node_modules/svgo/plugins/convertPathData.js:424:17
    at Array.filter (<anonymous>)
    at filters (/Users/dennis/work/github/wx-app/node_modules/svgo/plugins/convertPathData.js:272:17)
    at Object.exports.fn (/Users/dennis/work/github/wx-app/node_modules/svgo/plugins/convertPathData.js:79:20)
    at /Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo/plugins.js:59:45
    at Array.filter (<anonymous>)
    at monkeys (/Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at /Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo/plugins.js:66:17
    at Array.filter (<anonymous>)
    at monkeys (/Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at perItem (/Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo/plugins.js:77:12)
    at /Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo/plugins.js:18:24
    at Array.forEach (<anonymous>)
    at module.exports (/Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo/plugins.js:14:13)
    at /Users/dennis/work/github/wx-app/node_modules/svgo/lib/svgo.js:63:17
```

网上查了好像是要更新css-loader
https://stackoverflow.com/questions/60122210/issue-with-postcss-processing

package.json 和 demo 28 的一样https://github.com/Tencent/kbone/blob/db4e5fe3024c2475e20d1103033731511798dd40/examples/demo28/package.json
基本一样

**Comment by JuneAndGreen** [comment]
demo28 我特地删掉 package-lock 和 node_modules 试了下，无论是 npm run mp 还是 npm run build 都是正常的诶。我这边用的 node 是 v15.10.0 ，npm 是 v7.5.3。

![image](https://user-images.githubusercontent.com/7931744/114711925-1b946d00-9d62-11eb-8645-17f4deaf81b0.png)

> PS：webpack 是 v4.46.0，webpack-cli 是 v4.2.0。你也可以看看那边使用 demo28 报错的时候这些分别是什么版本？

**Comment by JuneAndGreen** [comment]
如果上面提到的版本都正确，却仍然有 buid 问题的话，可以发下 package-lock 文件给我。
