### ISSUE TITLE
使用kbone编译小程序后ide报错？

### ISSUE THREAD

**Issue by mumu1993** [Tencent/kbone#75]
VM1595:1 thirdScriptError
Cannot read property 'prototype' of undefined;at "pages/app/index" page lifeCycleMethod onLoad function
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (http://127.0.0.1:17407/appservice/common/chunk-vendors.js:25:47004)
    at l (http://127.0.0.1:17407/appservice/common/app.js:1:1303)
    at Object.<anonymous> (http://127.0.0.1:17407/appservice/common/chunk-vendors.js:39:11758)
    at l (http://127.0.0.1:17407/appservice/common/app.js:1:1303)
    at Object.<anonymous> (http://127.0.0.1:17407/appservice/common/app.js:1:4253)
    at Object.0 (http://127.0.0.1:17407/appservice/common/app.js:10:47450)
    at l (http://127.0.0.1:17407/appservice/common/app.js:1:1303)
    at Module.260 (http://127.0.0.1:17407/appservice/common/app.js:10:71136)
    at l (http://127.0.0.1:17407/appservice/common/app.js:1:1303)
    at o (http://127.0.0.1:17407/appservice/common/app.js:1:1117)
![image](https://user-images.githubusercontent.com/17734732/72203128-c7d20e80-34a2-11ea-8dbc-7afa5de27502.png)

[链接](https://developers.weixin.qq.com/community/develop/doc/000e4882fbc618dadeb99644c5b400?fromCreate=0)

**Comment by JuneAndGreen** [comment]
可以给下能复现出报错的demo么？我来定位下是什么问题。

**Comment by mumu1993** [comment]
> 可以给下能复现出报错的demo么？我来定位下是什么问题。



> 可以给下能复现出报错的demo么？我来定位下是什么问题。

怎么给你呢？可以加下你qq或者微信吗

**Comment by JuneAndGreen** [comment]
@mumu1993 如果可以开源，搞到 github 或者网盘上都可以，如果不方便开源可以发到邮箱 wx-miniprogram@qq.com

**Comment by JuneAndGreen** [comment]
@mumu1993 这里一直没有收到你的回复，请问问题是否已经解决了？没有的话可以提供一下 demo ？

**Comment by JuneAndGreen** [comment]
出现过同样问题，是第三方库实现问题，暂关闭，如有其他复现 demo 可 reopen。
